import type { Metadata } from "next";
import { Geist, Geist_Mono , Inter,} from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/app/context/AuthProvider";
import { ThemeProvider } from "@/app/darkMode/components/ThemeProvider";
import { ThemeWrapper } from "@/app/darkMode/components/ThemeWrapper";
import SwitchTheme from "@/app/darkMode/components/SwitchTheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
          <ThemeProvider
          >
            <ThemeWrapper>
              <AuthProvider>
                {children}
              </AuthProvider>
            </ThemeWrapper>
          </ThemeProvider>
      </body>
    </html>
  );
}